import type { Metadata } from "next";
import { RunningHead, Tags, Tag, OpenQuestion, Plate, Features, Feature, ProjectMeta, ProjectKicker, Folio } from "@/components/notebook";
import { Screen, Key } from "@/components/rack";

export const metadata: Metadata = {
  title: "Ashen Cathedral: a dungeon crawler built from scripts",
  description:
    "A first-person gothic dungeon crawler in Unreal Engine 5.8.2, inspired by Diablo 1. The rules live in engine-free C++ tested under sanitizers, and most assets are generated by Blender scripts. Paused.",
};

const SANITIZED = `clang++ -std=c++17 -Wall -Wextra -Werror \\
  -fsanitize=address,undefined \\
  Tests/RulesTests.cpp -o Saved/Tests/rules
ASAN_OPTIONS=detect_leaks=0 Saved/Tests/rules`;

export default function AshenCathedralPage() {
  return (
    <>
      <RunningHead
        brand="chong"
        meta={<ProjectMeta slug="ashen-cathedral" />}
        nav={
          <>
            <Key href="/">← all projects</Key>
          </>
        }
      />
      <main id="content" className="rack-main" tabIndex={-1}>

        <section className="detail-hero">
          <div>
            <ProjectKicker slug="ashen-cathedral" />
            <h1>A gothic dungeon crawler where nearly every asset comes out of a script.</h1>
            <p>
              An original first-person game for Unreal Engine 5.8.2, inspired by the
              cathedral descent in Diablo 1. You start in a village called Greyhollow,
              walk into the church, go down through the nave and two burial crypts, and
              fight the Butcher.
            </p>
            <p>
              It is paused as a work in progress. The part I would defend is the
              structure underneath: rules without an engine, and art without a mouse.
            </p>
          </div>
          <div>
            <Screen art="/screens/diablo-clone.png" tone="rust" />
            <Tags>
              <Tag>unreal 5.8</Tag>
              <Tag>c++</Tag>
              <Tag>blender python</Tag>
              <Tag>paused</Tag>
            </Tags>
          </div>
        </section>

        <section className="section">
          <div>
            <div className="section-kicker">The core</div>
            <h2>Game rules that compile without Unreal</h2>
            <p className="aside-note">
              Seven headers in <code>Source/AshenCathedral/Domain/</code>, 871 lines
              counted with <code>wc -l</code>.
            </p>
          </div>
          <div>
            <p>
              Combat, resources, items, trading, abilities, enemy stats, the town map
              and exploration are plain C++17 headers with no engine includes. The
              Unreal actors call into them. Damage and wind-up for the Butcher come from{" "}
              <code>enemyDamage</code> and <code>enemyWindup</code> in <code>Rules.h</code>,
              and the actor only decides when to ask for the enraged numbers.
            </p>
            <p>
              That split is what makes the tests cheap. <code>Scripts/test_rules.sh</code>{" "}
              compiles eight test programs with <code>clang++ -Werror</code> and
              AddressSanitizer plus UndefinedBehaviorSanitizer, then runs five Python
              unittest files for the asset pipeline. No editor, no GPU.
            </p>
            <Plate
              figure="FIG. 1 · one of eight sanitizer runs"
              caption="From Scripts/test_rules.sh. The other seven follow the same pattern for items, trade, enemies, exploration, town map, abilities and UI geometry."
            >
              <pre>
                <code>{SANITIZED}</code>
              </pre>
            </Plate>
            <p>
              The tests include hostile input. <code>Tests/ExplorationTests.cpp</code>{" "}
              checks that line of sight from <code>INT_MIN</code> to <code>INT_MAX</code>{" "}
              returns false and that a radius of <code>INT_MAX</code> returns nothing.
              I put those in after deciding the fog-of-war code should never trust its
              coordinates.
            </p>
          </div>
        </section>

        <section className="section">
          <div>
            <div className="section-kicker">The game</div>
            <h2>What is playable</h2>
          </div>
          <div>
            <Features>
              <Feature label="Built at runtime">
                The dungeon geometry and encounters are constructed by the game mode when
                the level loads. The map asset only holds a player start.
              </Feature>
              <Feature label="Fog of war">
                In the dungeon the minimap reveals cells by integer line of sight
                (<code>mapLineOfSight</code> in <code>Exploration.h</code>). Rays reveal a
                closed door but cannot see through it, or diagonally between two wall
                corners. Rooms you have left stay dimly drawn.
              </Feature>
              <Feature label="Grid inventory">
                A 10 by 4 pack. Each item kind has its own footprint, and drag, swap and
                equip all check the footprint against the grid.
              </Feature>
              <Feature label="The Butcher">
                Below half health he attacks faster. The README documents the numbers I
                set: damage 29 to 36 and wind-up 1.05 s to 0.72 s, defined in{" "}
                <code>enemyProfile</code>.
              </Feature>
              <Feature label="Greyhollow">
                A small village with a healer, a blacksmith who buys and sells, and the
                church you descend through. A labelled town map tracks your facing.
              </Feature>
              <Feature label="Short on purpose">
                The README calls it a short horror vertical slice. There is no mid-run
                save.
              </Feature>
            </Features>
          </div>
        </section>

        <section className="section">
          <div>
            <div className="section-kicker">The pipeline</div>
            <h2>Assets generated from code</h2>
            <p className="aside-note">
              <code>Scripts/</code> has 12 <code>generate_*.py</code> files and a set of{" "}
              <code>prepare_*</code> and <code>import_*</code> steps behind them.
            </p>
          </div>
          <div>
            <p>
              Props, the reliquary, the gate, the town and several character candidates
              are written as Blender Python. Importers then build materials, meshes,
              skeletal enemies, animation clips and the Cathedral map inside Unreal. If
              an asset looks wrong I change a script and re-run it.
            </p>
            <p>
              The Butcher shows how this goes. <code>SM_Butcher</code> was a procedural
              figure built from primitives, and it looked like it. The replacement
              starts from CC0 MakeHuman anatomy and goes through{" "}
              <code>Scripts/revise_butcher_detail.py</code> and{" "}
              <code>export_baked_butcher.py</code>, which bake the materials down for
              Unreal. <code>Docs/ART.md</code> records which source assets are
              replacements and which are legacy.
            </p>
            <Plate
              figure="FIG. 2 · the Butcher, idle, wind-up, walk, death"
              caption="A review sheet from ArtSource/Candidates/ButcherDetail/Review, rendered in Blender."
            >
              {/* eslint-disable-next-line @next/next/no-img-element -- static review render */}
              <img
                src="/ashen-cathedral/butcher-sheet.webp"
                alt="Four renders of the Butcher: standing with a cleaver, raising it overhead, walking, and lying dead."
                width={1280}
                height={427}
                loading="lazy"
              />
            </Plate>
            <Plate
              figure="FIG. 3 · the procedural Butcher it replaced"
              caption="SM_Butcher, a static mesh from primitives. Docs/ART.md keeps it as a legacy source asset."
            >
              {/* eslint-disable-next-line @next/next/no-img-element -- static preview render */}
              <img
                src="/ashen-cathedral/butcher-procedural.webp"
                alt="A blocky pink-orange Butcher figure with a plank mask and a cleaver."
                width={540}
                height={720}
                loading="lazy"
                className="plate-portrait"
              />
            </Plate>
          </div>
        </section>

        <section className="section">
          <div>
            <div className="section-kicker">The incident</div>
            <h2>My GPU fell off the bus, so the agents got limits</h2>
            <p className="aside-note">
              Sources: <code>Docs/GPU_INCIDENT.md</code> and <code>Docs/RESOURCE_LIMITS.md</code>.
            </p>
          </div>
          <div>
            <p>
              On 7 September 2026, while a packaged native build was running, the
              kernel log recorded NVIDIA Xid 79, “GPU has fallen off the bus.”
              Unreal logged <code>VK_ERROR_DEVICE_LOST</code> three seconds later and the
              display driver failed every query until the machine restarted, about two
              minutes after the Xid.
            </p>
            <p>
              The cause is still open. No temperature history existed, the log window
              showed no thermal or PCIe error beforehand, and the Unreal breadcrumb
              pointed at a buffer upload, which does not say much. The incident note
              says in so many words that it does not establish overheating and does not
              prove Lumen was to blame.
            </p>
            <p>
              What I could do was reduce the load and record better evidence. Heavy
              work now goes through <code>Scripts/resource_guard.py</code>, which runs it
              in a systemd user service with a 400% CPU quota, checks that quota before
              starting, allows one heavy job at a time, and polls temperature and memory
              every five seconds. If telemetry is missing it refuses to start. Unreal
              gets <code>-corelimit=3</code> and Blender gets four threads on CPU
              rendering. Previews are capped at 30 fps and 67% resolution.
            </p>
            <p>
              It was tested: 20 lightweight guard tests passed on 23 September, and on
              25 September three back-to-back Blender previews plus an indexer pushed the
              CPU to 88.5 °C and the guard stopped the job. Neither document claims the
              GPU fault is fixed, and GPU playtests stay stopped except for short guarded
              captures I authorised on 25 September.
            </p>
          </div>
        </section>

        <section className="section">
          <div>
            <div className="section-kicker">Where it stands</div>
            <h2>Paused, with a known gap</h2>
          </div>
          <div>
            <p>
              The repository has 4 commits, between 25 and 26 September 2026, and the
              README says the latest town, minimap, enemy and lighting revision is still
              in native validation. The launcher points at the previous standalone
              package until the new one passes. The GPU incident is why native
              runs are restricted.
            </p>
            <OpenQuestion>
              Is the fault the GPU, the PCIe link, the driver, or load I created? I can
              only say it has not recurred under the guard. That is not an explanation.
            </OpenQuestion>
          </div>
        </section>

        <section className="colophon">
          <div>
            Materials<strong>Unreal Engine 5.8.2, C++17, Blender Python</strong>
          </div>
          <div>
            Vintage<strong>September 2026</strong>
          </div>
          <div>
            Status<strong>Paused WIP</strong>
          </div>
          <div>
            Source<strong>private</strong>
          </div>
        </section>

      </main>
      <Folio slug="ashen-cathedral" />
    </>
  );
}
