// Natural Garden (art/briefs/garden.md): a cottage garden in soft daylight,
// painted as a botanical watercolour, its page set on cream cards against
// a low stone wall. Raws in art/raw/garden; prompts in art/prompts/garden.
//
// The scene is one painted plate per finish (the original mock with its UI
// painted out; the wall above the window left bare plaster for the
// masthead's words; the low wall taken out too: it stands against the
// page, so it is a sprite of its own, `wall-*`, that the page lays behind
// the cards), painted on past the mock's edges (the bleed) so it registers
// with the page at any aspect. Night is the same garden under a full moon,
// generated as an edit of the day plate, so the two register. The surfaces
// were generated by day only: by night the cards, buttons and labels are
// graded from the day's (`gain`, MOON), the same paper by moonlight.
//
// Wherever the mock's own pixels are what the page shows (everything outside
// the page's own copy, window, stone and cards), the scene is the mock's
// fine detail itself: the plate and the wall sprite carry its lettering,
// petals and stone grain, not a regeneration's (detail(), below), and each
// finished plate frame is sharpened once, lightly (SHARPEN), against the
// kit's resampling. The two buttons, the "Projects" stone, the brand's leaf
// and the mug's rim in front of the window are cut from the mock too
// (buttons(), plaque(), brandLeaf(), mugFront()): no prompt, only the
// original (art/raw/originals/garden.png).

import sharp from "sharp";
import { existsSync, mkdirSync, statSync } from "node:fs";

/* ---------- the plate: raws this recipe derives from others ----------
   Each is rebuilt when a source is newer, so a regeneration carries
   through. The sky layer of a finish (layer-sky-<f>) is made in two steps.
   1. Its core, the mock's 1672 x 941 frame (plate-core-<f>): the plate with
      the page painted out (plate-open-<f>), its upper middle taken from an
      edit of it left bare plaster (plaster-<f>-b: no rose or vine under the
      masthead's words or behind the window), and the five lettered props in
      its margins laid back in from the original mock itself, over an edit
      that paints them out (props-out-<f>), since every edit of the plate
      redrew their lettering. By night a prop is the original's pixels
      through the colour map the moonlit plate applies to the day's there.
   2. The bleed: the core painted on BLEED mock px either side and below
      (TAKES, art/prompts/garden/<take>.txt), the core pasted back over it
      exact, feathered into it at its sides and foot. */
const RAW = "art/raw/garden";
const raw = (name) => `${RAW}/${name}/${name}.png`;
const ORIGINAL = "art/raw/originals/garden.png";
const [W, H] = [1672, 941];
const BLEED = 320; // garden.css --sky-bleed-x, --sky-bleed-bottom
// The bleeds, each the core painted on from a grey canvas. Day's first take
// gave the watering can a second spout where the frame cut it; a night
// relit from the day's bleed lost the standing stone the frame cuts, so
// the finishes' margins are each their own painting of the same garden.
const TAKES = { day: "plate-bleed-day-c", night: "plate-bleed-night" };
// an unsharp mask: the painting plus `amount` of its difference from its blur
const SHARPEN = { amount: 0.9, sigma: 1 };
const stale = (out, srcs) => !existsSync(out) || srcs.some((src) => statSync(out).mtimeMs < statSync(src).mtimeMs);
const rgb = (file, w = W, h = H) => sharp(file).resize(w, h, { fit: "fill" }).removeAlpha().raw().toBuffer();
const write = async (name, buf, w = W, h = H) => {
  mkdirSync(`${RAW}/${name}`, { recursive: true });
  await sharp(buf, { raw: { width: w, height: h, channels: 3 } }).png().toFile(raw(name));
};

/** a weight inside a box [x0, y0, x1, y1], easing up from each edge over
 *  [left, top, right, bottom] px; an edge on the frame's stays hard */
const inside =
  ([x0, y0, x1, y1], [fl, ft, fr, fb]) =>
  (x, y) => {
    if (x < x0 || x > x1 || y < y0 || y > y1) return 0;
    const ease = (d, f) => (f <= 0 || d >= f ? 1 : 0.5 - 0.5 * Math.cos((Math.PI * d) / f));
    return ease(x - x0, x0 <= 0 ? 0 : fl) * ease(y - y0, y0 <= 0 ? 0 : ft) * ease(x1 - x, x1 >= W - 1 ? 0 : fr) * ease(y1 - y, y1 >= H - 1 ? 0 : fb);
  };

/** Lays `src` into `dst` (W x H RGB, in place) as the standard seamless
 *  composite does, in two bands: its detail over the narrow feather `fine`,
 *  its broad tone over the wide `broad`, so a region a shade lighter or
 *  warmer than the plate grades into it rather than standing as a patch.
 *  `shift` takes the source from that many px to the left (a clone). */
const SIGMA = 18;
const lay = async (dst, src, fine, broad, shift = 0) => {
  const low = (b) => sharp(b, { raw: { width: W, height: H, channels: 3 } }).blur(SIGMA).raw().toBuffer();
  const [ld, ls] = await Promise.all([low(dst), low(src)]);
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      const [wf, wb] = [fine(x, y), broad(x, y)];
      if (!wf && !wb) continue;
      const [i, j] = [(y * W + x) * 3, (y * W + Math.max(0, x - shift)) * 3];
      for (let k = 0; k < 3; k++) {
        const lo = ld[i + k] * (1 - wb) + ls[j + k] * wb;
        const hi = (dst[i + k] - ld[i + k]) * (1 - wf) + (src[j + k] - ls[j + k]) * wf;
        dst[i + k] = Math.max(0, Math.min(255, Math.round(lo + hi)));
      }
    }
};

/** The plate's dappled leaf shadows (the model's, in plate-open) are crisper
 *  and darker than the mock's soft shading of the plaster. In `box` (eased
 *  in over `fade` px), the mid band of tone (blur 3 minus blur 28) is held to
 *  `k` of its strength; the broad shading and the grain are left. */
const soften = async (buf, box, fade, k) => {
  const blur = (sigma) => sharp(buf, { raw: { width: W, height: H, channels: 3 } }).blur(sigma).raw().toBuffer();
  const [fine, broad] = await Promise.all([blur(3), blur(28)]);
  const w = inside(box, [fade, fade, fade, fade]);
  for (let y = box[1]; y <= box[3]; y++)
    for (let x = box[0]; x <= box[2]; x++) {
      const a = w(x, y) * (1 - k);
      if (!a) continue;
      const i = (y * W + x) * 3;
      for (let c = 0; c < 3; c++) buf[i + c] = Math.max(0, Math.min(255, Math.round(buf[i + c] - a * (fine[i + c] - broad[i + c]))));
    }
};

/* The lettered props, traced on the original (mock px): the board on the
   wall, the sign on the gate, the watering can, the two stones. `foot` is
   the band over which a prop fades out where the border's leaves grow in
   front of it. */
const PROPS = {
  sign: { polys: [[[15, 110], [100, 112], [163, 115], [168, 120], [169, 322], [165, 326], [18, 324], [15, 320]]] },
  gate: {
    polys: [
      [[1557, 331], [1561, 328], [1636, 328], [1640, 332], [1641, 419], [1637, 423], [1561, 423], [1557, 419]],
      [[1563, 316], [1568, 316], [1568, 330], [1563, 330]], // its wires
      [[1628, 316], [1633, 316], [1633, 330], [1628, 330]],
    ],
  },
  can: {
    polys: [
      [[17, 941], [18, 900], [19, 860], [20, 800], [20, 775], [21, 765], [30, 758], [32, 757], [37, 735], [47, 717], [65, 707], [88, 704], [110, 705], [130, 712], [142, 725], [150, 740], [154, 757], [156, 775], [158, 792], [160, 805], [162, 848], [175, 830], [186, 805], [190, 792], [200, 789], [212, 794], [220, 804], [220, 812], [208, 818], [196, 826], [185, 845], [172, 866], [168, 880], [170, 900], [173, 941]],
      [[0, 775], [12, 777], [24, 784], [30, 795], [31, 808], [28, 818], [21, 813], [21, 800], [16, 791], [8, 787], [0, 787]], // the rear handle
      [[0, 826], [6, 828], [16, 845], [25, 866], [29, 882], [23, 883], [15, 862], [6, 845], [0, 838]],
    ],
    holes: [[[44, 757], [50, 737], [65, 724], [88, 719], [110, 720], [127, 726], [137, 737], [142, 752], [140, 757], [120, 756], [90, 755], [60, 756]]], // through the top handle
    foot: [893, 941],
  },
  curious: { polys: [[[1556, 648], [1664, 648], [1671, 655], [1672, 655], [1672, 842], [1528, 842], [1531, 800], [1536, 740], [1541, 700], [1549, 668]]], foot: [800, 842] },
  playful: { polys: [[[1340, 895], [1345, 872], [1356, 860], [1385, 850], [1450, 844], [1520, 845], [1550, 848], [1572, 856], [1590, 870], [1600, 890], [1602, 912], [1598, 935], [1342, 935]]], foot: [908, 935] },
};

/** a prop's matte (W x H, one channel), its edge softened a pixel, and its
 *  bounding box */
const matte = async ({ polys, holes = [], foot }) => {
  const d = (ps) => ps.map((p) => `M${p.map((q) => q.join(",")).join(" L")} Z`).join(" ");
  const svg = `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg"><rect width="${W}" height="${H}"/><path d="${d(polys)}" fill="#fff"/>${holes.length ? `<path d="${d(holes)}"/>` : ""}</svg>`;
  const m = await sharp(Buffer.from(svg)).blur(1.1).extractChannel(0).raw().toBuffer();
  if (foot) {
    const [y0, y1] = foot;
    for (let y = y0; y < H; y++) {
      const f = y >= y1 ? 0 : 1 - ((y - y0) / (y1 - y0)) ** 1.5;
      for (let x = 0; x < W; x++) m[y * W + x] = Math.round(m[y * W + x] * f);
    }
  }
  let [x0, y0, x1, y1] = [W, H, -1, -1];
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) if (m[y * W + x] > 2) [x0, y0, x1, y1] = [Math.min(x0, x), Math.min(y0, y), Math.max(x1, x), Math.max(y1, y)];
  return { m, box: [x0, y0, x1, y1] };
};

/** the affine colour map (3 x [r g b 1]) taking `from` to `to` where the
 *  matte is solid: least squares, by the normal equations */
const colourMap = (from, to, { m, box: [x0, y0, x1, y1] }) => {
  const A = Array.from({ length: 4 }, () => new Float64Array(4));
  const B = Array.from({ length: 3 }, () => new Float64Array(4));
  for (let y = y0; y <= y1; y++)
    for (let x = x0; x <= x1; x++) {
      if (m[y * W + x] <= 200) continue;
      const i = (y * W + x) * 3;
      const v = [from[i], from[i + 1], from[i + 2], 255];
      for (let r = 0; r < 4; r++) {
        for (let c = 0; c < 4; c++) A[r][c] += v[r] * v[c];
        for (let k = 0; k < 3; k++) B[k][r] += v[r] * to[i + k];
      }
    }
  const solve = (b) => {
    const a = A.map((row, r) => [...row, b[r]]);
    for (let c = 0; c < 4; c++) {
      const p = a.reduce((best, _, r) => (r >= c && Math.abs(a[r][c]) > Math.abs(a[best][c]) ? r : best), c);
      [a[c], a[p]] = [a[p], a[c]];
      for (let r = 0; r < 4; r++) if (r !== c) for (let k = 4, f = a[r][c] / a[c][c]; k >= c; k--) a[r][k] -= f * a[c][k];
    }
    return a.map((row, r) => row[4] / row[r]);
  };
  return B.map(solve);
};

/* ---------- the vine's right end, by day ----------
   The mock's vine runs on past the nav's first word (x 1008-1068, behind the
   word "index"), so it is cut short. A fade (the first cut) leaves a feathered
   ruler line; a straight cut a step of tone (the leaves shade the plaster
   round them, the plate's plaster beyond is lighter). So the cut is a path
   down the plaster between the leaves (the cheapest of those that keep to
   x 970-1032, a pixel a row: dynamic programming over how far each pixel
   stands from the plaster), and what is laid past x 960 is only the leaves
   and roses themselves (alpha from that distance, the colour what the plaster
   leaves of them), over the plate's plaster. The mock's grey shade behind the
   vine, above the window, stays out of them: it would end in a hard line at
   the window's edge, which a tablet's crop shows. */
const PLASTER = [232, 214, 194];
const smooth = (t) => (t <= 0 ? 0 : t >= 1 ? 1 : t * t * (3 - 2 * t));
/** how much of a pixel is leaf or petal: how far its hue stands from the
 *  plaster's (green or pink, where the cream's red - green and green - blue
 *  are both about 20), or how dark it is (a leaf's shade); the plaster's own
 *  shadow, a darker cream, is not */
const leafAlpha = (rgb, i) => {
  const [r, g, b] = [rgb[i], rgb[i + 1], rgb[i + 2]];
  const chroma = Math.hypot(r - g - (PLASTER[0] - PLASTER[1]), g - b - (PLASTER[1] - PLASTER[2]));
  return Math.max(smooth((chroma - 20) / 24), smooth((120 - (0.299 * r + 0.587 * g + 0.114 * b)) / 40));
};
/** x of the cut at each row 0-70: 1022 above y 20, where the top leaf's tip
 *  reaches past the cut, then the cheapest path down to the window's edge */
const vineEnd = (rgb) => {
  const [y0, y1, x0, x1] = [24, 70, 970, 1032];
  const n = x1 - x0 + 1;
  // clear of the word: "index" starts at x 1012 (halo and all, 1000) and its
  // letters stand from y 27 to 42
  const cost = (j, i) => (y0 + j < 46 && x0 + i > 994 ? Infinity : leafAlpha(rgb, ((y0 + j) * W + x0 + i) * 3) + 0.002 * Math.abs(x0 + i - 1000));
  const best = [Float64Array.from({ length: n }, (_, i) => cost(0, i))];
  const from = [new Int16Array(n)];
  for (let j = 1; j <= y1 - y0; j++) {
    const [b, f] = [new Float64Array(n).fill(Infinity), new Int16Array(n)];
    for (let i = 0; i < n; i++)
      for (const di of [-1, 0, 1]) {
        const v = best[j - 1][i + di] + cost(j, i) + 0.01 * Math.abs(di);
        if (v < b[i]) [b[i], f[i]] = [v, i + di];
      }
    best.push(b);
    from.push(f);
  }
  const path = new Float64Array(y1 + 1).fill(1022);
  let i = best[y1 - y0].indexOf(Math.min(...best[y1 - y0]));
  for (let j = y1 - y0; j >= 0; j--) [path[y0 + j], i] = [x0 + i, from[j][i]];
  for (let y = 20; y < y0; y++) path[y] = 1022 + ((path[y0] - 1022) * (y - 20)) / (y0 - 20);
  return path;
};
/** Lays the leaves of `src` inside `box` over `dst`, left of the cut `end[y]`
 *  (a pixel and a half of ease), the plaster they stand on left to `dst`;
 *  where `placed` (a weight) has already laid the picture itself, they are
 *  not laid again. */
const layLeaves = (dst, src, [x0, y0, x1, y1], end, placed = () => 0) => {
  for (let y = y0; y <= y1; y++) {
    const foot = Math.min(1, y1 + 1 - y);
    for (let x = x0; x <= x1; x++) {
      const i = (y * W + x) * 3;
      const [a, keep] = [leafAlpha(src, i), foot * smooth((end[y] - x + 1.5) / 3) * (1 - placed(x, y))];
      if (a * keep < 0.004) continue;
      for (let c = 0; c < 3; c++) {
        // the leaf's own colour (the plaster unmixed from the pixel), over the plate's
        const leaf = Math.max(0, Math.min(255, (src[i + c] - (1 - a) * PLASTER[c]) / Math.max(a, 0.05)));
        dst[i + c] = Math.round(dst[i + c] + keep * a * (leaf - dst[i + c]));
      }
    }
  }
};

const core = async (finish) => {
  const name = `plate-core-${finish}`;
  const srcs = [raw(`plate-open-${finish}`), raw(`plaster-${finish}-b`), raw(`props-out-${finish}`), ORIGINAL, raw("plate-open-day")];
  if (!srcs.every(existsSync) || !stale(raw(name), [...srcs, import.meta.filename])) return;
  const [open, plaster, cleared, original, openDay] = await Promise.all(srcs.map((f) => rgb(f)));
  const out = Buffer.from(open);
  // the bare plaster over the upper middle (x 690-1352, where both are plain
  // plaster at its sides), its own rose vine at the right end first cloned
  // out with its plaster from 150 px to the left
  const patched = Buffer.from(plaster);
  const vine = [1240, 0, 1356, 200];
  await lay(patched, plaster, inside(vine, [14, 0, 6, 14]), inside(vine, [50, 0, 10, 50]), 150);
  const upper = [690, 0, 1352, 350];
  await lay(out, patched, inside(upper, [20, 0, 6, 20]), inside(upper, [60, 0, 14, 60]));
  // The vine and its roses over the top edge, from the nav's left to the
  // window's corner: the plaster above took them out with the masthead's
  // words (x 1082+, which stay out). By day the mock's own; by night the
  // night plate's.
  // It must end clear of the nav's first word: by day (the light rice) that
  // starts at x 1008, so the vine stops at x 1004; by night the longest rice
  // name ("cosmic dusk") starts it at x 954, so it stops short of the big
  // rose (x 905-967), which would sit behind the "i" of "index". It ends on
  // the vine's own gaps, not on a feathered ruler line (below). The plaster
  // under it eases out into the plate's before the window's top edge (y 71),
  // as it must where the window does not stand over the seam (a tablet's
  // crop); the leaves themselves run on to the edge, where the mock's touch it.
  if (finish === "day") {
    // the mock's plaster, tone and detail, as far as the roses (x 960) ...
    const reach = [690, 0, 960, 66];
    const fine = inside(reach, [26, 0, 36, 16]);
    await lay(out, original, fine, inside(reach, [44, 0, 76, 30]));
    // ... and past them, and below where the plaster eases out, only its
    // leaves, laid over the plate's plaster, so the cut carries no step of
    // tone: the vine cut along a path down its own gaps
    layLeaves(out, original, [690, 0, 1030, 70], vineEnd(original), fine);
  } else {
    const arch = [690, 0, 906, 66];
    await lay(out, open, inside(arch, [26, 0, 18, 16]), inside(arch, [44, 0, 40, 30]));
  }
  // the plate's leaf shadows on the plaster beside the headline and behind
  // the nav's words, as soft as the mock's
  await soften(out, [380, 0, 700, 400], 40, 0.2);
  // The plate's own bush right of "Try it live" rises 70 px above the mock's
  // (the mock has bare plaster there down to y 343): the plaster 118 px above
  // it is laid over it, so where the page shows the plate (the headline's
  // column) there is no bush, and where it shows the mock (detail(), x 641 on)
  // the two grade into each other as plaster.
  const bush = [628, 258, 700, 348];
  const above = Buffer.from(out);
  for (let y = bush[1]; y <= bush[3]; y++) out.copy(above, (y * W + bush[0]) * 3, ((y - 118) * W + bush[0]) * 3, ((y - 118) * W + bush[2] + 1) * 3);
  await lay(out, above, inside(bush, [16, 16, 0, 12]), inside(bush, [30, 30, 0, 24]));
  await soften(out, [996, 0, 1352, 74], 24, 0.3);
  for (const prop of Object.values(PROPS)) {
    const cut = await matte(prop);
    const [x0, y0, x1, y1] = cut.box;
    const clear = [x0 - 16, y0 - 16, x1 + 16, y1 + 16];
    await lay(out, cleared, inside(clear, [12, 12, 12, 12]), inside(clear, [40, 40, 40, 40]));
    const map = finish === "day" ? null : colourMap(openDay, open, cut);
    for (let y = y0; y <= y1; y++)
      for (let x = x0; x <= x1; x++) {
        const a = cut.m[y * W + x] / 255;
        if (!a) continue;
        const i = (y * W + x) * 3;
        const c = [original[i], original[i + 1], original[i + 2]];
        for (let k = 0; k < 3; k++) {
          const v = map ? map[k][0] * c[0] + map[k][1] * c[1] + map[k][2] * c[2] + map[k][3] * 255 : c[k];
          out[i + k] = Math.max(0, Math.min(255, Math.round(out[i + k] * (1 - a) + v * a)));
        }
      }
  }
  await write(name, out);
};

const sky = async (finish) => {
  const name = `layer-sky-${finish}`;
  const srcs = [raw(TAKES[finish]), raw(`plate-detail-${finish}`), import.meta.filename];
  if (!srcs.every(existsSync) || !stale(raw(name), srcs)) return;
  const [BW, BH] = [W + 2 * BLEED, H + BLEED];
  const [out, c] = await Promise.all([rgb(srcs[0], BW, BH), rgb(srcs[1])]);
  // the core exact, eased in from its sides and foot over FEATHER px (its
  // top is the frame's)
  const FEATHER = 24;
  const ease = (d) => (d >= FEATHER ? 1 : 0.5 - 0.5 * Math.cos((Math.PI * Math.max(0, d)) / FEATHER));
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      const a = ease(Math.min(x, W - 1 - x, H - 1 - y));
      const [i, o] = [(y * W + x) * 3, (y * BW + x + BLEED) * 3];
      for (let k = 0; k < 3; k++) out[o + k] = Math.round(out[o + k] * (1 - a) + c[i + k] * a);
    }
  // Sharpened once, over the whole painting: the page shows it through two
  // resamplings (build-kit.mjs frames it at 2654 px for 2312 and the browser
  // scales it back) and a q78 encode, which took the plate to 40-50% of the
  // mock's edge energy (Laplacian variance) at 1:1; this gives it back
  // (measured 95-110%, the wall's detail alone being 100% unsharpened).
  const low = await sharp(out, { raw: { width: BW, height: BH, channels: 3 } }).blur(SHARPEN.sigma).raw().toBuffer();
  for (let i = 0; i < out.length; i++) out[i] = Math.max(0, Math.min(255, Math.round(out[i] + SHARPEN.amount * (out[i] - low[i]))));
  await write(name, out, BW, BH);
};

/* ---------- the wall, laid back on the mock ----------
   The wall sprite (wall-<f>, the mock's low wall and what stands on its
   ledge, drawn by the model in the plate's frame) holds its things only
   roughly where the mock has them: the mug 8 px left of it, the books 7 and
   the cat 8 px right, the potted rose 20 (a stretch that grows along the
   ledge), all a few px high. The page lays it between the window and the
   cards, so it is re-registered: for blocks on the ledge, between the window's foot
   and the cards' top (and the rose's column), the displacement that lays
   the sprite on the picture it should match is found (zero-mean SSD), and
   the sprite is warped by the field those give, smoothed. Day matches the
   mock; night matches the day's registered wall (a night edit of it). */
const SPRITE_ZONES = [[420, 575, 300, 1530], [280, 500, 1360, 1500]]; // y0, y1, x0, x1
const alphaOf = (png) => sharp(png).resize(W, H, { fit: "fill" }).ensureAlpha().extractChannel(3).raw().toBuffer();
const greyOf = (png) => sharp(png).resize(W, H, { fit: "fill" }).greyscale().raw().toBuffer();
/** the sprite's displacement samples [x, y, dx, dy] against `ref` (grey): the sprite's content at (x + dx, y + dy) is what the ref has at (x, y) */
const displacements = (ref, flat, alpha, accept) => {
  const [bs, step, R] = [40, 16, 36];
  const out = [];
  for (const [zy0, zy1, zx0, zx1] of SPRITE_ZONES)
    for (let y = zy0; y + bs <= zy1; y += step)
      for (let x = zx0; x + bs <= zx1; x += step) {
        // only where the sprite itself is, and the ref has something to match
        let cover = 0, mean = 0, spread = 0;
        for (let j = 0; j < bs; j += 4) for (let i = 0; i < bs; i += 4) cover += alpha[(y + j) * W + x + i];
        if (cover / (bs / 4) ** 2 < 235) continue;
        for (let j = 0; j < bs; j += 2) for (let i = 0; i < bs; i += 2) mean += ref[(y + j) * W + x + i];
        mean /= (bs / 2) ** 2;
        for (let j = 0; j < bs; j += 2) for (let i = 0; i < bs; i += 2) spread += (ref[(y + j) * W + x + i] - mean) ** 2;
        spread = Math.sqrt(spread / (bs / 2) ** 2);
        if (spread < 8) continue;
        let best = [Infinity, 0, 0];
        for (let dy = -R; dy <= R; dy++)
          for (let dx = -R; dx <= R; dx++) {
            if (y + dy < 0 || x + dx < 0 || y + dy + bs > H || x + dx + bs > W) continue;
            let m = 0;
            for (let j = 0; j < bs; j += 2) for (let i = 0; i < bs; i += 2) m += flat[(y + j + dy) * W + x + i + dx];
            m /= (bs / 2) ** 2;
            let sum = 0;
            for (let j = 0; j < bs; j += 2) for (let i = 0; i < bs; i += 2) {
              const d = ref[(y + j) * W + x + i] - mean - (flat[(y + j + dy) * W + x + i + dx] - m);
              sum += d * d;
            }
            if (sum < best[0]) best = [sum, dx, dy];
          }
        if (Math.sqrt(best[0] / (bs / 2) ** 2) / spread < accept) out.push([x + bs / 2, y + bs / 2, best[1], best[2]]);
      }
  // a sample far from its neighbours' median is a false match
  return out.filter((p) => {
    const near = out.filter((o) => o !== p && Math.hypot(o[0] - p[0], o[1] - p[1]) < 75);
    if (near.length < 3) return true;
    const med = (k) => near.map((o) => o[k]).sort((a, b) => a - b)[near.length >> 1];
    return Math.hypot(p[2] - med(2), p[3] - med(3)) < 6;
  });
};
/** the sprite (RGBA, W x H) resampled through the field the samples give (a Gaussian-weighted mean, on a 16 px grid, bilinear between) */
const warp = (sprite, samples) => {
  const [G, SIGMA2] = [16, 2 * 55 * 55];
  const [gw, gh] = [Math.ceil(W / G) + 1, Math.ceil(H / G) + 1];
  const grid = [new Float32Array(gw * gh), new Float32Array(gw * gh)];
  for (let j = 0; j < gh; j++)
    for (let i = 0; i < gw; i++) {
      let sw = 0, sx = 0, sy = 0, near = [Infinity, 0, 0];
      for (const [px, py, dx, dy] of samples) {
        const d2 = (px - i * G) ** 2 + (py - j * G) ** 2;
        if (d2 < near[0]) near = [d2, dx, dy];
        const w = Math.exp(-d2 / SIGMA2);
        sw += w; sx += w * dx; sy += w * dy;
      }
      [grid[0][j * gw + i], grid[1][j * gw + i]] = sw > 1e-3 ? [sx / sw, sy / sw] : [near[1], near[2]];
    }
  const at = (a, x, y) => {
    const [i, j] = [Math.min(gw - 2, Math.floor(x / G)), Math.min(gh - 2, Math.floor(y / G))];
    const [fx, fy, k] = [x / G - i, y / G - j, j * gw + i];
    return (a[k] * (1 - fx) + a[k + 1] * fx) * (1 - fy) + (a[k + gw] * (1 - fx) + a[k + gw + 1] * fx) * fy;
  };
  const out = Buffer.alloc(W * H * 4);
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      const [sx, sy] = [x + at(grid[0], x, y), y + at(grid[1], x, y)];
      const [x0, y0] = [Math.floor(sx), Math.floor(sy)];
      const [fx, fy] = [sx - x0, sy - y0];
      const c = [0, 0, 0, 0];
      for (const [ox, oy, w] of [[0, 0, (1 - fx) * (1 - fy)], [1, 0, fx * (1 - fy)], [0, 1, (1 - fx) * fy], [1, 1, fx * fy]]) {
        const k = (Math.min(H - 1, Math.max(0, y0 + oy)) * W + Math.min(W - 1, Math.max(0, x0 + ox))) * 4;
        const a = sprite[k + 3] / 255; // bilinear in premultiplied colour
        c[0] += sprite[k] * a * w; c[1] += sprite[k + 1] * a * w; c[2] += sprite[k + 2] * a * w; c[3] += a * w;
      }
      const o = (y * W + x) * 4;
      out[o + 3] = Math.round(c[3] * 255);
      for (let k = 0; k < 3; k++) out[o + k] = c[3] > 0 ? Math.max(0, Math.min(255, Math.round(c[k] / c[3]))) : 0;
    }
  return out;
};

const wall = async (finish) => {
  const name = `wall-reg-${finish}`;
  const srcs = [raw(`wall-${finish}`), raw(`plate-core-${finish}`), finish === "day" ? ORIGINAL : raw("wall-reg-day")];
  if (!srcs.every(existsSync) || !stale(raw(name), srcs)) return;
  const [sprite, base, target] = srcs;
  const baseRGB = await sharp(base).resize(W, H, { fit: "fill" }).removeAlpha().png().toBuffer();
  const ref = finish === "day" ? await greyOf(target) : await sharp(await sharp(raw("plate-core-day")).composite([{ input: target }]).png().toBuffer()).greyscale().raw().toBuffer();
  let rgba = await sharp(sprite).resize(W, H, { fit: "fill" }).ensureAlpha().raw().toBuffer();
  // two passes: the second takes up what the field's smoothing left
  for (let pass = 0; pass < 2; pass++) {
    const png = await sharp(rgba, { raw: { width: W, height: H, channels: 4 } }).png().toBuffer();
    // the sprite over its plate, as the page shows it, against what it should look like
    const flat = await sharp(baseRGB).composite([{ input: png }]).greyscale().raw().toBuffer();
    const samples = displacements(ref, flat, await alphaOf(png), finish === "day" ? 0.7 : 0.85);
    if (samples.length < 40) throw new Error(`garden wall: only ${samples.length} blocks matched for ${finish}`);
    rgba = warp(rgba, samples);
  }
  mkdirSync(`${RAW}/${name}`, { recursive: true });
  await sharp(rgba, { raw: { width: W, height: H, channels: 4 } }).png().toFile(raw(name));
};


/* ---------- the mock's own detail ----------
   The plate and the wall are generations: softer than the mock they were
   painted from, and the wall's things (the mug, the books, the cat, the pot)
   a few px off its (warped onto it, 1 to 5 px short of the mock's rows). But
   they are the mock's scene, and where nothing of the page's own stands over
   it the two are the same picture, so there the page's scene is the mock's
   pixels, not the generation's. What the page draws itself (the brand and
   the copy, the nav, the window, the "Projects" stone, the cards) is painted
   out of the plate, and stays the plate's; round it the mock fades in.
   The page lays the wall over the plate (garden.css .showcase::before), so
   the difference between the mock and what the two make together is added
   back to both, so the pair composites to the mock, whatever the wall's
   alpha: the plate takes it as far as the wall does not cover it (1 - a), the
   wall twice that where it does (2 - a), since (1 - a)(1 - a) + a(2 - a) = 1.
   Where the wall's own clip (garden.css) shows the plate alone, the plate
   takes it all; the wall's hidden pixels take it too, as a phone shows them.
   By night the scene is the mock graded by the night's own tone over the
   day's (a soft per-channel ratio of the two generations), not the night's
   generation with the mock's detail added: its lettering is the model's own,
   a pixel or two from the mock's, and the two would show as one doubled. */
const EXCLUDED = [
  // [x0, y0, x1, y1, feather]: mock px of what the page draws over the plate
  [284, 0, 641, 350, [20, 20, 40, 20]], // the brand, the tagline, the headline, the pitch and the buttons, on bare plaster; right of "Try it live" (ends 643) the mock's own pixels, clean wall, not the plate's bush, which rises 70 px higher
  [996, 0, 1352, 78, 20], // the nav
  [906, 0, 998, 70, 14], // the vine's end over the nav: by night it stops at x 906 (the rose there would sit behind "cosmic dusk")
  [689, 69, 1339.5, 421.5, [4, 24, 4, 4]], // the window (its foot rests on the books' top); its top edge eases over 24 px, so a crop that shows the plate without the window over it (a tablet's) has no line where the mock's vine and plaster end
  [114, 504, 318, 574, 6], // the "Projects" stone
  [176, 574, 508, 822, 5], [516, 574, 842, 822, 5], [850, 574, 1170, 822, 5], [1178, 574, 1509, 822, 5], // the cards
];
/** how far the mock's pixel is the page's scene: 1 clear of everything
 *  the page draws, easing to 0 at its edge (a box's feather is one width, or
 *  one per side: left, top, right, bottom) */
const open = (x, y) => {
  let w = 1;
  for (const [x0, y0, x1, y1, f] of EXCLUDED) {
    const [fl, ft, fr, fb] = Array.isArray(f) ? f : [f, f, f, f];
    const d = Math.hypot(Math.max(x0 - x, 0, x - x1) / (x < x0 ? fl : fr), Math.max(y0 - y, 0, y - y1) / (y < y0 ? ft : fb));
    if (d < 1) w = Math.min(w, d * d * (3 - 2 * d));
  }
  return w;
};
/** where the wall sprite shows: the page clips it round the watering can and
 *  the lettered stone (garden.css .showcase::before, keep in step) */
const wallClip = async () => {
  const pts = [[0, 0], [W, 0], [W, 642], [1538, 646], [1524, 830], [1524, H], [178, H], [178, 694], [0, 694]];
  const svg = `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg"><rect width="${W}" height="${H}"/><polygon points="${pts.map((p) => p.join(",")).join(" ")}" fill="#fff"/></svg>`;
  return sharp(Buffer.from(svg)).extractChannel(0).raw().toBuffer();
};
/* ---------- the mug in front of the window ----------
   In the mock the mug stands in front of the monitor: its rim, and the
   handle's loop over the monitor's lower left corner (x 691-727, y 396-421).
   The page's window is a layer of its own over the wall, so it would cover
   them; this is the mug's own pixels there (the mock's), lifted off the dark
   monitor behind them (alpha from how far each pixel stands from the
   monitor's near-black toward the china's cream, the colour what that
   leaves, so an edge carries none of the monitor), for the page to lay over
   the window (garden.css .launchpad-window::after). Cropped to its own
   outline, so the kit's trim leaves it as it is; its colour is the scene's
   (`target`: by night the wall's mug as the page shows it). */
const MUG_BOX = [686, 396, 731, 426];
const MONITOR = [32, 33, 35];
const mugFront = async (finish, mock, target) => {
  const [x0, y0, x1, y1] = MUG_BOX;
  const [w, h] = [x1 - x0, y1 - y0];
  const rgba = Buffer.alloc(w * h * 4);
  let [bx0, by0, bx1, by1] = [w, h, -1, -1];
  for (let y = 0; y < h; y++)
    for (let x = 0; x < w; x++) {
      const [px, py] = [x0 + x, y0 + y];
      const i = py * W + px;
      const l = 0.299 * mock[i * 4] + 0.587 * mock[i * 4 + 1] + 0.114 * mock[i * 4 + 2];
      // china is bright; its shaded inner edge (down to ~120) is still china
      let a = Math.min(1, Math.max(0, (l - 38) / (150 - 38)));
      if (px > 727) a = 0; // the monitor's rim line beyond the handle
      a *= Math.min(1, Math.max(0, (424 - py) / 2)); // the window's foot is at 421.5, its contact shadow just under: past them the wall has the same pixels
      if (a < 0.02) continue;
      for (let c = 0; c < 3; c++) {
        // over the monitor, what it leaves of the pixel; under the window's foot the wall holds these very pixels, so as they are
        const v = py < 422 ? (target[i * 3 + c] - (1 - a) * MONITOR[c]) / a : target[i * 3 + c];
        rgba[(y * w + x) * 4 + c] = Math.max(0, Math.min(255, Math.round(v)));
      }
      rgba[(y * w + x) * 4 + 3] = Math.round(a * 255);
      [bx0, by0, bx1, by1] = [Math.min(bx0, x), Math.min(by0, y), Math.max(bx1, x), Math.max(by1, y)];
    }
  const name = `mug-front-${finish}`;
  mkdirSync(`${RAW}/${name}`, { recursive: true });
  await sharp(rgba, { raw: { width: w, height: h, channels: 4 } }).extract({ left: bx0, top: by0, width: bx1 - bx0 + 1, height: by1 - by0 + 1 }).png().toFile(raw(name));
  console.log(`garden ${name}: x ${x0 + bx0}-${x0 + bx1}, y ${y0 + by0}-${y0 + by1} (${bx1 - bx0 + 1} x ${by1 - by0 + 1})`);
};
/** the wall's lettered things (the mug and the books; the pot of roses),
 *  where a night painting's lettering must give way to the mock's */
const LETTERED = [[586, 386, 962, 520, 10], [1356, 390, 1496, 524, 10]];
const lettered = (x, y) => {
  let z = 0;
  for (const [x0, y0, x1, y1, f] of LETTERED) {
    const d = Math.hypot(Math.max(x0 - x, 0, x - x1), Math.max(y0 - y, 0, y - y1));
    z = Math.max(z, d >= f ? 0 : 1 - (d / f) ** 2 * (3 - (2 * d) / f));
  }
  return z;
};
// the scale (sigma, px) below which the mock's detail is taken, by night
const NIGHT_BAND = 2.5;
/** a box blur (radius `r`, two passes, edges clamped) of a W x H field */
const boxBlur = (f, r) => {
  const pass = (src, dx) => {
    const out = new Float32Array(src.length);
    const [n, len] = dx ? [H, W] : [W, H];
    for (let k = 0; k < n; k++) {
      const at = (j) => src[dx ? k * W + Math.min(len - 1, Math.max(0, j)) : Math.min(len - 1, Math.max(0, j)) * W + k];
      let sum = 0;
      for (let j = -r; j <= r; j++) sum += at(j);
      for (let j = 0; j < len; j++) {
        out[dx ? k * W + j : j * W + k] = sum / (2 * r + 1);
        sum += at(j + r + 1) - at(j - r);
      }
    }
    return out;
  };
  return pass(pass(pass(pass(f, 1), 1), 0), 0);
};
const detail = async (finish) => {
  const day = finish === "day";
  const srcs = [raw(`plate-core-${finish}`), raw(`wall-reg-${finish}`), ORIGINAL, ...(day ? [] : [raw("plate-core-day"), raw("wall-reg-day")]), import.meta.filename];
  if (!srcs.every(existsSync) || !stale(raw(`plate-detail-${finish}`), srcs)) return;
  const rgba = (f) => sharp(f).resize(W, H, { fit: "fill" }).ensureAlpha().raw().toBuffer();
  const [core, wall, mock, coreD, wallD, clip] = await Promise.all([rgba(srcs[0]), rgba(srcs[1]), rgba(ORIGINAL), day ? null : rgba(srcs[3]), day ? null : rgba(srcs[4]), wallClip()]);
  /** the page's picture: the wall over the plate, its clip applied */
  const compose = (p, w) => {
    const out = new Float32Array(W * H * 3);
    for (let i = 0; i < W * H; i++) {
      const a = (w[i * 4 + 3] / 255) * (clip[i] / 255);
      for (let c = 0; c < 3; c++) out[i * 3 + c] = p[i * 4 + c] * (1 - a) + w[i * 4 + c] * a;
    }
    return out;
  };
  const here = compose(core, wall);
  // By night: the tone the finish keeps over the day's, per channel, soft;
  // the mock's pixels under it (`graded`), and what is kept of the night's own
  // painting (its moon, its lit windows, its glow: the broad band, `lowHere`)
  const low = (f32, sigma) => sharp(Buffer.from(f32.map((v) => Math.round(v))), { raw: { width: W, height: H, channels: 3 } }).blur(sigma).raw().toBuffer();
  let grade = null, graded = null, lowHere = null, lowGraded = null, gain = null;
  if (!day) {
    const [lh, lt] = await Promise.all([low(here, 8), low(compose(coreD, wallD), 8)]);
    grade = Float32Array.from(lh, (v, i) => Math.min(2, Math.max(0.2, v / Math.max(1, lt[i]))));
    graded = Float32Array.from({ length: W * H * 3 }, (_, i) => Math.min(255, mock[((i / 3) | 0) * 4 + (i % 3)] * grade[i]));
    [lowHere, lowGraded] = await Promise.all([low(here, NIGHT_BAND), low(graded, NIGHT_BAND)]);
    // The night is not the day's contrast scaled: a moonlit painting keeps
    // its detail's contrast (about 1.4 to 2 times what the day's, scaled by
    // the tone, would have). The mock's detail is laid in at the contrast of
    // the painting's own, region by region (the ratio of the two details'
    // local energy), so it is the mock's shapes at the night's weight.
    const energy = (hi) => {
      const sq = new Float32Array(W * H);
      for (let i = 0; i < W * H; i++) sq[i] = (hi(i * 3) ** 2 + hi(i * 3 + 1) ** 2 + hi(i * 3 + 2) ** 2) / 3;
      return boxBlur(sq, 10);
    };
    const [eHere, eGraded] = [energy((j) => here[j] - lowHere[j]), energy((j) => graded[j] - lowGraded[j])];
    gain = Float32Array.from(eHere, (v, i) => Math.min(3, Math.max(0.8, Math.sqrt((v + 25) / (eGraded[i] + 25)))));
  }
  // what the page's scene is, wherever it is the mock's: by day the mock's
  // pixel; by night its fine detail on the painting's own broad tone (and
  // where the wall's lettering is, on the mock's own: the painting's lettering
  // is a pixel or two off it, and would double it)
  const target = new Float32Array(W * H * 3);
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      const i = y * W + x;
      const z = day ? 0 : lettered(x + 0.5, y + 0.5);
      for (let c = 0; c < 3; c++) target[i * 3 + c] = day ? mock[i * 4 + c] : gain[i] * (graded[i * 3 + c] - lowGraded[i * 3 + c]) + z * lowGraded[i * 3 + c] + (1 - z) * lowHere[i * 3 + c];
    }
  const plate = Buffer.alloc(W * H * 3);
  const sprite = Buffer.from(wall);
  const clamp = (v) => Math.max(0, Math.min(255, Math.round(v)));
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      const i = y * W + x;
      const w = open(x + 0.5, y + 0.5);
      const a = wall[i * 4 + 3] / 255;
      const shown = a * (clip[i] / 255);
      for (let c = 0; c < 3; c++) {
        const d = w * (target[i * 3 + c] - here[i * 3 + c]);
        plate[i * 3 + c] = clamp(core[i * 4 + c] + (1 - shown) * d);
        // pixels the wall does not cover carry the plate's, a clean edge to resample
        sprite[i * 4 + c] = a < 0.01 ? plate[i * 3 + c] : clamp(wall[i * 4 + c] + (clip[i] ? 2 - shown : 1) * d);
      }
    }
  await mugFront(finish, mock, target);
  mkdirSync(`${RAW}/plate-detail-${finish}`, { recursive: true });
  mkdirSync(`${RAW}/wall-detail-${finish}`, { recursive: true });
  await Promise.all([
    sharp(plate, { raw: { width: W, height: H, channels: 3 } }).png().toFile(raw(`plate-detail-${finish}`)),
    sharp(sprite, { raw: { width: W, height: H, channels: 4 } }).png().toFile(raw(`wall-detail-${finish}`)),
  ]);
};

/* ---------- the brand's leaf, cut from the mock ----------
   The spray after "chong" is bolder and a good deal bigger in the mock than
   the generated one (a leaf 44 px across, in a dark, saturated green), so it
   is the mock's own, lifted off the plaster: alpha from how far each pixel
   stands from the plaster's cream, the colour what that leaves, at three
   times the size. Cropped to its own outline (logged, mock px, for
   garden.css .brand .led). */
const BRAND_LEAF = { box: [446, 10, 500, 66], plaster: [246, 232, 215] };
const brandLeaf = async () => {
  const name = "leaf-brand";
  if (!existsSync(ORIGINAL) || !stale(raw(name), [ORIGINAL, import.meta.filename])) return;
  const { box: [x0, y0, x1, y1], plaster } = BRAND_LEAF;
  const [w, h, k] = [x1 - x0, y1 - y0, 3];
  const up = await sharp(ORIGINAL).extract({ left: x0, top: y0, width: w, height: h }).resize(w * k, h * k, { kernel: "lanczos3" }).removeAlpha().raw().toBuffer();
  const rgba = Buffer.alloc(w * k * h * k * 4);
  let [bx0, by0, bx1, by1] = [w * k, h * k, -1, -1];
  for (let i = 0; i < w * k * h * k; i++) {
    const d = Math.hypot(up[i * 3] - plaster[0], up[i * 3 + 1] - plaster[1], up[i * 3 + 2] - plaster[2]);
    const t = Math.min(1, Math.max(0, (d - 24) / (38 - 24)));
    const a = t * t * (3 - 2 * t);
    if (a < 0.06) continue;
    for (let c = 0; c < 3; c++) rgba[i * 4 + c] = Math.max(0, Math.min(255, Math.round((up[i * 3 + c] - (1 - a) * plaster[c]) / a)));
    rgba[i * 4 + 3] = Math.round(a * 255);
    const [x, y] = [i % (w * k), (i / (w * k)) | 0];
    [bx0, by0, bx1, by1] = [Math.min(bx0, x), Math.min(by0, y), Math.max(bx1, x), Math.max(by1, y)];
  }
  mkdirSync(`${RAW}/${name}`, { recursive: true });
  await sharp(rgba, { raw: { width: w * k, height: h * k, channels: 4 } }).extract({ left: bx0, top: by0, width: bx1 - bx0 + 1, height: by1 - by0 + 1 }).png().toFile(raw(name));
  console.log(`garden ${name}: x ${x0 + bx0 / k}-${x0 + (bx1 + 1) / k}, y ${y0 + by0 / k}-${y0 + (by1 + 1) / k}`);
};

/* ---------- the "Projects" stone, cut from the mock ----------
   The mock's sign is a flat board of weathered limestone, rough at its edge,
   with a nail at each of its two left corners and a dark chip at each right
   one (the generated stone had a bright rivet in all four and a darker rim).
   It is the mock's own, cut along the board's outline (the pixels that are
   board, not the ivy behind: warm and light, joined, holes filled, clipped to
   the board's measured box) with its lettering and sprig painted out as the
   buttons' are, at three times the size, for the page to 9-slice
   (garden.css .showcase-title). */
const PLAQUE = { crop: [108, 498, 214, 80], board: [117.5, 507, 314, 568.5], lettering: [160, 515, 300, 566] };
const plaque = async () => {
  const name = "label-mock";
  if (!existsSync(ORIGINAL) || !stale(raw(name), [ORIGINAL, import.meta.filename])) return;
  const [cx, cy, w, h] = PLAQUE.crop;
  const src = await sharp(ORIGINAL).extract({ left: cx, top: cy, width: w, height: h }).removeAlpha().raw().toBuffer();
  const lum = (i) => 0.299 * src[i * 3] + 0.587 * src[i * 3 + 1] + 0.114 * src[i * 3 + 2];
  const [bx0, by0, bx1, by1] = PLAQUE.board;
  const morph = (a, r, grow) => {
    const o = new Uint8Array(w * h);
    for (let y = 0; y < h; y++)
      for (let x = 0; x < w; x++) {
        let v = grow ? 0 : 1;
        for (let dy = -r; dy <= r; dy++)
          for (let dx = -r; dx <= r; dx++) {
            const [xx, yy] = [x + dx, y + dy];
            const q = xx >= 0 && yy >= 0 && xx < w && yy < h ? a[yy * w + xx] : 0;
            v = grow ? v || q : v && q;
          }
        o[y * w + x] = v ? 1 : 0;
      }
    return o;
  };
  let board = new Uint8Array(w * h);
  for (let i = 0; i < w * h; i++) {
    const [r, g, b] = [src[i * 3], src[i * 3 + 1], src[i * 3 + 2]];
    const [x, y] = [cx + (i % w) + 0.5, cy + ((i / w) | 0) + 0.5];
    board[i] = lum(i) > 120 && r >= g - 6 && r - b > 14 && r - b < 100 && x > bx0 && x < bx1 && y > by0 && y < by1 ? 1 : 0;
  }
  board = morph(morph(board, 2, false), 2, true); // specks off
  board = morph(morph(board, 3, true), 3, false); // gaps closed
  // the largest piece, its holes filled
  const lab = new Int32Array(w * h);
  let [top, topSize, n] = [0, 0, 0];
  const flood = (from, ok, mark) => {
    const stack = [from];
    mark(from);
    let count = 0;
    while (stack.length) {
      const j = stack.pop();
      count++;
      const [x, y] = [j % w, (j / w) | 0];
      for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
        const [xx, yy] = [x + dx, y + dy];
        if (xx >= 0 && yy >= 0 && xx < w && yy < h && ok(yy * w + xx)) {
          mark(yy * w + xx);
          stack.push(yy * w + xx);
        }
      }
    }
    return count;
  };
  for (let i = 0; i < w * h; i++)
    if (board[i] && !lab[i]) {
      n++;
      const c = flood(i, (k) => board[k] && !lab[k], (k) => (lab[k] = n));
      if (c > topSize) [top, topSize] = [n, c];
    }
  const solid = new Uint8Array(w * h);
  const outside = new Uint8Array(w * h);
  for (let i = 0; i < w * h; i++) solid[i] = lab[i] === top ? 1 : 0;
  flood(0, (k) => !solid[k] && !outside[k], (k) => (outside[k] = 1));
  for (let i = 0; i < w * h; i++) solid[i] = outside[i] ? 0 : 1;
  // the lettering and the sprig: dark ink, or green, in their own box (the
  // nails, in the board's corners, are left)
  const [lx0, ly0, lx1, ly1] = PLAQUE.lettering;
  const ink = new Uint8Array(w * h);
  for (let y = 0; y < h; y++)
    for (let x = 0; x < w; x++) {
      const i = y * w + x;
      const [px, py] = [cx + x, cy + y];
      if (px < lx0 || px > lx1 || py < ly0 || py > ly1) continue;
      if (lum(i) < 95 || src[i * 3 + 1] > src[i * 3] - 3) ink[i] = 1;
    }
  const mask = morph(ink, 3, true);
  const fill = Float32Array.from(src);
  for (let pass = 0; pass < 500; pass++)
    for (let y = 1; y < h - 1; y++)
      for (let x = 1; x < w - 1; x++) {
        const i = y * w + x;
        if (mask[i]) for (let c = 0; c < 3; c++) fill[i * 3 + c] = (fill[(i - 1) * 3 + c] + fill[(i + 1) * 3 + c] + fill[(i - w) * 3 + c] + fill[(i + w) * 3 + c]) / 4;
      }
  let seed = 4321;
  const grain = () => ((seed = (seed * 1664525 + 1013904223) >>> 0) / 4294967296 - 0.5) * 3.46;
  const clean = Buffer.alloc(w * h * 3);
  for (let i = 0; i < w * h; i++) for (let c = 0; c < 3; c++) clean[i * 3 + c] = Math.max(0, Math.min(255, Math.round(fill[i * 3 + c] + (mask[i] ? grain() * 3 : 0))));
  const k = 3;
  const [W2, H2] = [w * k, h * k];
  const [up, matte] = await Promise.all([
    sharp(clean, { raw: { width: w, height: h, channels: 3 } }).resize(W2, H2, { kernel: "lanczos3" }).raw().toBuffer(),
    sharp(Buffer.from(solid.map((v) => v * 255)), { raw: { width: w, height: h, channels: 1 } }).resize(W2, H2, { kernel: "lanczos3" }).blur(1).extractChannel(0).raw().toBuffer(),
  ]);
  const rgba = Buffer.alloc(W2 * H2 * 4);
  for (let i = 0; i < W2 * H2; i++) {
    up.copy(rgba, i * 4, i * 3, i * 3 + 3);
    // a pixel in from the outline, so none of the ivy comes with it
    rgba[i * 4 + 3] = Math.max(0, Math.min(255, (matte[i] - 128) * 2 + 128));
  }
  mkdirSync(`${RAW}/${name}`, { recursive: true });
  await sharp(rgba, { raw: { width: W2, height: H2, channels: 4 } }).png().toFile(raw(name));
};

/* ---------- the buttons, cut from the mock ----------
   The mock's two buttons are not clean tiles: "Try it live" is an aged
   parchment tag (a darker cream, brown staining along its edges and corners,
   a little wear at the corners, a brown rim) and "Join the alpha" a flat,
   mottled moss felt with a slightly rough, darker edge, both about 6 px
   round. Generated boards came back too clean or too torn, so these are the
   mock's own, cut out along their rounded outlines (measured, mock px) with
   the lettering painted out: the pixels under a letter (and the halo round
   it) are filled from the board round them, diffusing in, with the board's
   grain laid back. Upscaled to the 120 px height the kit's tile step stores
   (build-kit.mjs `tiles`), so it resamples nothing. */
const BUTTONS = {
  "button-cream-d": { box: [508.3, 287.6, 642.6, 337.9], radius: 6.5, lettering: "dark" },
  "button-green-d": { box: [293.8, 287.5, 487.8, 338.1], radius: 5.5, lettering: "light" },
};
const TILE_H = 120;
const buttons = async () => {
  if (!existsSync(ORIGINAL)) return;
  for (const [name, { box: [bx0, by0, bx1, by1], radius, lettering }] of Object.entries(BUTTONS)) {
    if (!stale(raw(name), [ORIGINAL, import.meta.filename])) continue;
    const PAD = 4;
    const [cx, cy] = [Math.floor(bx0) - PAD, Math.floor(by0) - PAD];
    const [w, h] = [Math.ceil(bx1) + PAD - cx, Math.ceil(by1) + PAD - cy];
    const src = await sharp(ORIGINAL).extract({ left: cx, top: cy, width: w, height: h }).removeAlpha().raw().toBuffer();
    const lum = Float32Array.from({ length: w * h }, (_, i) => 0.299 * src[i * 3] + 0.587 * src[i * 3 + 1] + 0.114 * src[i * 3 + 2]);
    // inside the board, clear of its rim (which is part of the art)
    const inside = (x, y) => x + cx + 0.5 > bx0 + 4 && x + cx + 0.5 < bx1 - 4 && y + cy + 0.5 > by0 + 4 && y + cy + 0.5 < by1 - 4;
    // the lettering is what stands out from the median of its 11 x 11 surround
    // (dark ink and its pale halo on the parchment, pale letters on the felt)
    const at = (x, y) => lum[Math.min(h - 1, Math.max(0, y)) * w + Math.min(w - 1, Math.max(0, x))];
    const letter = new Uint8Array(w * h);
    for (let y = 0; y < h; y++)
      for (let x = 0; x < w; x++) {
        if (!inside(x, y)) continue;
        const around = [];
        for (let dy = -5; dy <= 5; dy++) for (let dx = -5; dx <= 5; dx++) around.push(at(x + dx, y + dy));
        const d = lum[y * w + x] - around.sort((a, b) => a - b)[60];
        if (lettering === "dark" ? Math.abs(d) > 14 : d > 14) letter[y * w + x] = 1;
      }
    // grown by 3 px so the letters' soft edges go with them
    const mask = new Uint8Array(w * h);
    for (let y = 0; y < h; y++)
      for (let x = 0; x < w; x++)
        if (letter[y * w + x]) for (let dy = -3; dy <= 3; dy++) for (let dx = -3; dx <= 3; dx++) if (x + dx >= 0 && y + dy >= 0 && x + dx < w && y + dy < h) mask[(y + dy) * w + x + dx] = 1;
    const fill = Float32Array.from(src);
    for (let pass = 0; pass < 400; pass++)
      for (let y = 1; y < h - 1; y++)
        for (let x = 1; x < w - 1; x++) {
          const i = y * w + x;
          if (mask[i]) for (let c = 0; c < 3; c++) fill[i * 3 + c] = (fill[(i - 1) * 3 + c] + fill[(i + 1) * 3 + c] + fill[(i - w) * 3 + c] + fill[(i + w) * 3 + c]) / 4;
        }
    // the board's grain (a spread of about 1.5 levels, measured where there
    // is no lettering) laid into what was filled, so the patches are not flat
    const clean = Buffer.alloc(w * h * 3);
    let seed = 1234;
    const grain = () => ((seed = (seed * 1664525 + 1013904223) >>> 0) / 4294967296 - 0.5) * 3.46;
    for (let i = 0; i < w * h; i++) for (let c = 0; c < 3; c++) clean[i * 3 + c] = Math.max(0, Math.min(255, Math.round(fill[i * 3 + c] + (mask[i] ? grain() * 1.5 : 0))));
    // cut along the measured outline, 0.4 px in (so none of the plaster
    // round it comes with it), at the tile's height
    const k = TILE_H / (by1 - by0);
    const [W2, H2] = [Math.round(w * k), Math.round(h * k)];
    const up = await sharp(clean, { raw: { width: w, height: h, channels: 3 } }).resize(W2, H2, { kernel: "lanczos3" }).raw().toBuffer();
    const [x0, y0, x1, y1] = [(bx0 - cx + 0.4) * k, (by0 - cy + 0.4) * k, (bx1 - cx - 0.4) * k, (by1 - cy - 0.4) * k];
    const svg = `<svg width="${W2}" height="${H2}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%"/><rect x="${x0}" y="${y0}" width="${x1 - x0}" height="${y1 - y0}" rx="${radius * k}" fill="#fff"/></svg>`;
    const matte = await sharp(Buffer.from(svg)).extractChannel(0).raw().toBuffer();
    const rgba = Buffer.alloc(W2 * H2 * 4);
    for (let i = 0; i < W2 * H2; i++) {
      up.copy(rgba, i * 4, i * 3, i * 3 + 3);
      rgba[i * 4 + 3] = matte[i];
    }
    mkdirSync(`${RAW}/${name}`, { recursive: true });
    await sharp(rgba, { raw: { width: W2, height: H2, channels: 4 } }).png().toFile(raw(name));
  }
};

await buttons();
await brandLeaf();
await plaque();
await Promise.all(["day", "night"].map(core));
await wall("day");
await wall("night");
await Promise.all(["day", "night"].map((f) => detail(f).then(() => sky(f))));

// moonlight on cream: the same board cooled to a pale blue-grey parchment,
// light enough that its deckle, rim and grain still read and dark ink on it
// holds at better than 4.5:1 (garden.css night inks)
const MOON = [0.7, 0.75, 0.88];
// paint keeps its colour a little better than paper under the moon
const MOON_PAINT = [0.62, 0.66, 0.78];
// a sprite painted into the scene: no cast shadow (the painting has its own)
const PAINTED = ["0:0:1:0", "0:0:1:0"];

const kit = {
  raw: "garden",
  sheet: {
    normal: ["6:11:14:0.22", "1:2:2.5:0.3"],
    // lifted toward the sun: a longer, wider, softer shadow
    hover: ["16:34:28:0.48", "4:8:8:0.2"],
    pressed: ["3:5:8:0.2", "0.5:1:1.5:0.36"],
    flat: ["5:9:12:0.2", "0.5:1.5:2:0.32"],
    hoverFlags: ["--catch=0", "--sheen=0.06"],
    // focus: the card lies on a mount of moss-green board, cut clean
    mount: 12,
    mountCut: "crisp",
  },
  // Cards of thick cream board with softly rounded, worn corners and a thin
  // tan edge (the mock's project cards). The rim takes the key light a
  // little, upper left.
  sheets: [
    { name: "sheet-day", src: "card-day", shade: 0.1, lift: 0.03, under: "4a6140" },
    { name: "sheet-night", src: "card-day", gain: MOON, shade: 0.1, lift: 0.03, under: "4a6140" },
  ],
  tile: {
    normal: ["2:5:5:0.28", "0:1:1.2:0.34"],
    // lifted toward the sun, its upper edge catching it
    hover: ["5:12:6:0.44", "1:2.5:1.5:0.3"],
    pressed: ["1:2:2.5:0.2", "0:1:1:0.38"],
    hoverFlags: ["--catch=0.5", "--catch-width=6", "--sheen=0.08", "--light=fff2d6"],
    pressedFlags: ["--catch=0.4", "--catch-width=8", "--dim=0.9"],
  },
  // painted buttons: cream parchment the neutral, moss green the primary
  // (the mock's "Try it live" and "Join the alpha"). Focus is a channel
  // cut just inside the edge: moss on the cream, cream on the moss.
  tiles: [
    { name: "tile-day", src: "button-cream-d", ring: "4a6140" },
    { name: "tile-night", src: "button-cream-d", gain: MOON, ring: "4a6140" },
    { name: "tile-signal", src: "button-green-d", ring: "f4e7cf" },
    { name: "tile-signal-night", src: "button-green-d", gain: MOON_PAINT, ring: "f4e7cf" },
  ],
  // glazed beads, graded by night with the paint
  pins: { src: "pins", night: MOON_PAINT },
  tapes: [
    // a page's kicker on a strip of weathered copper plant label
    { name: "tape-day", src: "tape-day" },
    { name: "tape-night", src: "tape-day", gain: MOON_PAINT },
    // inline code chalked on a slip of slate
    { name: "chip-day", src: "chip-day" },
    { name: "chip-night", src: "chip-day", gain: 0.8 },
  ],
  props: [
    // The low stone wall across the first screen and the things on its
    // ledge (the mug, the books, the sleeping cat, the potted rose), in the
    // plate's own framing: the page lays it behind the cards, its ledge
    // just under the window (garden.css .showcase::before). The
    // build trims it to what shows (day 1672 x 670 from y 193, night 1672 x 680
    // from y 187 of the 1672 x 941 frame: garden.css --wall-top, --wall-h).
    { name: "wall-day", srcs: [{ src: "wall-detail-day" }, { src: "wall-reg-day" }, { src: "wall-day" }], resize: { width: 1672 }, pad: 0, shadow: PAINTED },
    { name: "wall-night", srcs: [{ src: "wall-detail-night" }, { src: "wall-reg-night" }, { src: "wall-reg-day", gain: MOON_PAINT }, { src: "wall-night" }, { src: "wall-day", gain: MOON_PAINT }], resize: { width: 1672 }, pad: 0, shadow: PAINTED },
    // the mug's rim and handle, lifted off the monitor, for the page to lay
    // over the window (kept at the size it was cut, 1 px to a mock px)
    { name: "mug-front-day", srcs: [{ src: "mug-front-day" }], resize: { width: 1000, withoutEnlargement: true }, pad: 0, shadow: PAINTED },
    { name: "mug-front-night", srcs: [{ src: "mug-front-night" }], resize: { width: 1000, withoutEnlargement: true }, pad: 0, shadow: PAINTED },
    // the stone label a row is named on (the mock's "Projects"): a slab of
    // limestone with an iron rivet in each corner, 9-sliced by the page
    // outside the rivets
    { name: "label-day", srcs: [{ src: "label-mock" }, { src: "label-day" }], resize: { width: 600 }, pad: 10, shadow: ["2:4:6:0.24", "0.5:1:1.5:0.3"] },
    { name: "label-night", srcs: [{ src: "label-mock", gain: MOON }, { src: "label-day", gain: MOON }], resize: { width: 600 }, pad: 10, shadow: ["2:4:6:0.36", "0.5:1:1.5:0.4"] },
    // the sprigs beside a name, as the mock paints them: a broad three-leaf
    // sprig after a title (the flagship, each card, the row's stone), a
    // fuller four-leaf spray after the brand. By moonlight the brand's
    // spray, on the plaster beside the pale name (and on a phone over the
    // ivy's shadow), is lit to a pale moonlit sage as the name is; a title's
    // sprig keeps its green, being mostly on the cards' parchment.
    { name: "sprig-day", srcs: [{ src: "sprig-leaf" }], resize: { width: 160, height: 160, fit: "inside" }, pad: 2, shadow: PAINTED },
    { name: "sprig-night", srcs: [{ src: "sprig-leaf", gain: [0.8, 0.86, 0.92] }], resize: { width: 160, height: 160, fit: "inside" }, pad: 2, shadow: PAINTED },
    { name: "spray-day", srcs: [{ src: "leaf-brand" }, { src: "sprig-spray" }], resize: { width: 160, height: 160, fit: "inside" }, pad: 2, shadow: PAINTED },
    { name: "spray-night", srcs: [{ src: "leaf-brand", gain: [1.25, 1.3, 1.75] }, { src: "sprig-spray", gain: [1.25, 1.3, 1.75] }], resize: { width: 160, height: 160, fit: "inside" }, pad: 2, shadow: PAINTED },
  ],
  scene: {
    finishes: ["day", "night"],
    // the plate is the whole scene (layer-sky-*, above), with its bleed
    layers: ["sky"],
    bleed: { x: BLEED, bottom: BLEED },
  },
};

export default kit;
